### ISSUE TITLE
getindex(o::PyObject, s::Symbol) is deprecated

### ISSUE THREAD

**Issue by Tarlan0001** [cstjean/ScikitLearn.jl#55]
I got this warning.

```
┌ Warning: `getindex(o::PyObject, s::Symbol)` is deprecated in favor of dot overloading (`getproperty`) so elements should now be accessed as e.g. `o.s` instead of `o[:s]`.
│   caller = import_sklearn() at Skcore.jl:120
```

How to resolve it?

**Comment by cstjean** [comment]
It's fixed in the latest master. Do `]add ScikitLearn#master`. 

Someone just needs to write the Project.toml file so that we can do a release

**Comment by tosalonijain** [comment]
Dear @cstjean , I tried doing that but maybe I am still getting the warning, I also updated the ScikitLearn package. But, nothing changed.

**Comment by cstjean** [comment]
Hi, I'm very sorry that I haven't had the time to properly maintain this package. However, the warnings are really just that - warnings, that can be ignored for now. Everything should still work correctly.

**Comment by tosalonijain** [comment]
It's absolutely fine @cstjean , it's better for now I ignore them. Anyways, thanks for addressing :)

**Comment by alexmorley** [comment]
@cstjean I actually missed one of the depwarnings that should have been fixed in #53  :disappointed: .

I'm done writing my thesis in the next week or so and will fix then :)

**Comment by alexmorley** [comment]
@tosalonijain or Tarlan0001 if you fancied giving it a go it won't not be too hard to fix (famous last words) although it involves a tiny bit of [metaprogramming](https://docs.julialang.org/en/v1/manual/metaprogramming/index.html). 

It's just because PyCall recently allowed the sytax `pythonobject.attribute` as oppsed to `pythonobject[:attribute]` which is much nicer so the warning are to encourage people to switch... ScikitLearn.jl has a bit of metaprogramming to generate all of the function calls for scikitlearn without having to write them individually, and one of those is still generating functions that do this `pythonobject[:attribute]`.

**Comment by cstjean** [comment]
This should be completely fixed now, right? If anyone hits any of these warnings, please report it here.
